### ISSUE TITLE
Key error 16 when no phase 5 node.

### ISSUE THREAD

**Issue by TheRoboKitten** [dragonchain/dragonchain#142]
Still: 
```{"transaction_id": "ca69121e-5fe8-4618-8d8c-a87d323d6171"}jacob@jacob-desktop:~/DragonChain/scripts$ screen -r processor1
ERROR:apscheduler.executors.default:Job "trigger_handler (trigger: cron[second='*/5'], next run at: 2017-11-19 20:24:35 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "processing.py", line 163, in trigger_handler
    self.notify(event_name=1, current_block_id=get_current_block_id())
  File "processing.py", line 126, in notify
    observer["callback"](config=observer["config"], **kwargs)
  File "processing.py", line 319, in _execute_phase_1
    self.network.public_broadcast(block_info, phase)
  File "/opt/dragonchain/blockchain/network.py", line 712, in public_broadcast
    for node in self.peer_dict[PHASE_5_NODE]:
KeyError: 16
``` 
No phase 5 nodes at all. Phase 4 broadcast turned off. Is phase5 broadcast mandatory to broadast my transactions to other nodes? My databases are all setup correctly and all. 

> Shrug

Any and all help is appreciated

**Comment by TheRoboKitten** [comment]
I think this is resolved? I'm not sure. I don't see any transactions replicating across nodes. Though, this infrastructure is nice.

The one thing I am confused on is transaction SSC Provisioning:

Provision:
```
{
  "header": {
    "create_ts": XXXXXXXXX,
    "business_unit": "NemoTechnologies",
    "family_of_business": "NemoTechnologies",
    "line_of_business": "NemoTechnologies",
    "owner": "NemoTechnologies",
    "transaction_type": "TT_PROVISION_SSC",
    "actor": "NemoTechnologies",
    "entity": "NemoTechnologies"
  },
  "payload": {
    "phase": 4,
    "smart_contract": {
      "transaction_type": "DIFFERENTTYPESPERPROVISION",
      "ssc": "ZGVmIGZ1bmMoc2VsZiwgdHJhbnNhY3Rpb24pOiByZXR1cm4gVHJ1ZQ=="
    },
    "data": "DATACANBEHERE",
    "test": "print 'TEST'",
    "criteria": ["phase"],
    "requirements": ["uuid", "time"],
    "version": 1
  }
}
```
Transaction:
```
{
  "header": {
    "create_ts": XXXXXXXXX,
    "business_unit": "NemoTechnologies",
    "family_of_business": "NemoTechnologies",
    "line_of_business": "NemoTechnologies",
    "owner": "NemoTechnologies",
    "transaction_type": "TT_PROVISION_SSC",
    "actor": "NemoTechnologies",
    "entity": "NemoTechnologies"
  },
  "payload": {
    "phase": 4,
    "smart_contract": {
      "transaction_type": "DIFFERENTTYPESPERPROVISION",
      "ssc": "ZGVmIGZ1bmMoc2VsZiwgdHJhbnNhY3Rpb24pOiByZXR1cm4gVHJ1ZQ==" <----- Basically the key in this scenario per transaction_type?
    },
    "data": "DATACANBEHERE",
    "test": "print 'TEST'",
    "criteria": ["phase"],
    "requirements": ["uuid", "time"],
    "version": 1
  }
}
```

**Comment by TheRoboKitten** [comment]
This raises another question.......... How do I approve a subscription?
