### ISSUE TITLE
Inconsistent (extemely) inconsistent subscription issue.

### ISSUE THREAD

**Issue by Gr1dd** [dragonchain/dragonchain#144]
subscribing to node1 from node 0: status "new" no error in docker.
Subscribing to node0 from node1: rejected with errors.
Node1:
```
txn_service_1  | {u'header': {u'family_of_business': u'NemoTechnologies', u'line_of_business': u'NemoTechnologies', u'actor': u'NemoTechnologies', u'transaction_type': u'TT_SUB_REQ', u'business_unit': u'NemoTechnologies', u'create_ts': 1511209983, u'owner': u'NemoTechnologies', u'entity': u'NemoTechnologies'}, u'payload': {u'subscription': {u'subscribed_node_id': u'8a7b667a-ce11-11e7-8484-d7d79ad3d5b2', u'phase_criteria': 4, u'host': u'71.52.69.194', u'create_ts': 1511209983, u'criteria': [u'phase'], u'node_owner': u'NemoTechnologies', u'port': u'8083'}}}
processor1_1   | Phase 1 Verify Start.
processor1_1   | Time bounds: 1511209980 - 1511209985
processor1_1   | WARNING:verifier-service:An exception of type AttributeError occurred. Arguments:
processor1_1   | ("'list' object has no attribute 'items'",)
processor1_1   | Phase 1 Verify Start.
processor1_1   | Time bounds: 1511209985 - 1511209990
processor1_1   | (<class 'thrift.Thrift.TApplicationException'>, TApplicationException(None,), <traceback object at 0x1754e18>)
processor1_1   | WARNING:network-manager:error attempting to ping an unregistered node: disconnecting node
processor1_1   | ERROR:apscheduler.executors.default:Job "ConnectionManager.refresh_registered (trigger: cron[second='*/5'], next run at: 2017-11-20 20:33:15 UTC)" raised an exception
processor1_1   | Traceback (most recent call last):
processor1_1   |   File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
processor1_1   |     retval = job.func(*job.args, **job.kwargs)
processor1_1   |   File "/opt/dragonchain/blockchain/network.py", line 234, in refresh_registered
processor1_1   |     for peer in self.connections:
processor1_1   | RuntimeError: Set changed size during iteration
processor1_1   | Phase 1 Verify Start.
processor1_1   | Time bounds: 1511209990 - 1511209995
processor4_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor3_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor2_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor1_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor1_1   | Phase 1 Verify Start.
processor1_1   | Time bounds: 1511209995 - 1511210000
processor3_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor1_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor2_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor4_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor1_1   | Phase 1 Verify Start.
processor1_1   | Time bounds: 1511210000 - 1511210005
processor3_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor2_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor4_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor1_1   | WARNING:network-manager:Subscription[sub_id:5700f4e8-5bc6-48d2-8f76-142219082dd4][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
```
Node1: 
```
[{"header": {"status": "rejected", "family_of_business": "NemoTechnologies", "block_id": 15794353, "line_of_business": "NemoTechnologies", "entity": "NemoTechnologies", "create_ts": 1511209983, "owner": "NemoTechnologies", "creator_id": null, "actor": "NemoTechnologies", "transaction_type": "TT_SUB_REQ", "business_unit": "NemoTechnologies", "transaction_id": "d8f5e6b8-5153-4529-ab8b-14fd4761e23f", "transaction_ts": 1511209983}, "payload": {"subscription": {"subscribed_node_id": "8a7b667a-ce11-11e7-8484-d7d79ad3d5b2", "phase_criteria": 4, "host": "71.52.69.194", "create_ts": 1511209983, "criteria": ["phase"], "node_owner": "NemoTechnologies", "port": "8083"}}, "signature": {"stripped_hash": "b04aa0f5d0030bb78a0fa22ff0415142a366eca30d75d38bd53a08cdc0c5c8e5922267a1e5a493b6a14c22372a60076ce0292d64d08fc2ffb1a185af40603d3f", "hash": "f5158fc6ad6c533591f914b2ddcd6f5d8ca0058795df631edfbc71cacd6614dc0b9b9bb0602351b71f3421bbcbad8d705c0645bd9fba1cedf231b5b34123a452", "public_key": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+Rsl6z8xqFlWz9es9jZxE2wwpvzm\nx6al05cgl7n4FxkFNgjGrFGwAK4fE4LnvEr7BtBUya5FTwvwY8TjfoLWnQ==\n-----END PUBLIC KEY-----\n", "signature_ts": 1511209983, "signatory": "transaction-service", "signature": "+HEek4bQn3Y4EEwdxcNCYccIozwWYgVXsVsmy+aiQYubmueOhG689GUYoLEGZriexXMhy8vjQJw8\n4TCQrtI+kg==\n"}}]
```
Node1:
```
processor2_1   | Traceback (most recent call last):
processor2_1   |   File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
processor2_1   |     retval = job.func(*job.args, **job.kwargs)
processor2_1   |   File "/opt/dragonchain/blockchain/network.py", line 512, in timed_receipt_request
processor2_1   |     vrs = self.get_vrs(node, ver_ids)  # verifications matching given verification ids
processor2_1   |   File "/opt/dragonchain/blockchain/network.py", line 625, in get_vrs
processor2_1   |     verifications = node.client.transfer_data(node.pass_phrase, received, unreceived)
processor2_1   |   File "/opt/dragonchain/blockchain/gen/messaging/BlockchainService.py", line 419, in transfer_data
processor2_1   |     return self.recv_transfer_data()
processor2_1   |   File "/opt/dragonchain/blockchain/gen/messaging/BlockchainService.py", line 444, in recv_transfer_data
processor2_1   |     raise TApplicationException(TApplicationException.MISSING_RESULT, "transfer_data failed: unknown result")
processor2_1   | TApplicationException: transfer_data failed: unknown result
processor3_1   | ERROR:apscheduler.executors.default:Job "ConnectionManager.timed_receipt_request (trigger: cron[second='*/300'], next run at: 2017-11-20 20:40:00 UTC)" raised an exception
processor3_1   | Traceback (most recent call last):
processor3_1   |   File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
processor3_1   |     retval = job.func(*job.args, **job.kwargs)
processor3_1   |   File "/opt/dragonchain/blockchain/network.py", line 511, in timed_receipt_request
processor3_1   |     ver_ids = node.client.receipt_request(node.pass_phrase)
processor3_1   |   File "/opt/dragonchain/blockchain/gen/messaging/BlockchainService.py", line 386, in receipt_request
processor3_1   |     return self.recv_receipt_request()
processor3_1   |   File "/opt/dragonchain/blockchain/gen/messaging/BlockchainService.py", line 409, in recv_receipt_request
processor3_1   |     raise TApplicationException(TApplicationException.MISSING_RESULT, "receipt_request failed: unknown result")
processor3_1   | TApplicationException: receipt_request failed: unknown result
```
Node0:
```
{"header": {"status": "new", "family_of_business": "NemoTechnologies", "block_id": null, "line_of_business": "NemoTechnologies", "entity": "NemoTechnologies", "create_ts": 1511209834, "owner": "NemoTechnologies", "creator_id": null, "actor": "NemoTechnologies", "transaction_type": "TT_SUB_REQ", "business_unit": "NemoTechnologies", "transaction_id": "62a5065c-bac6-430b-a73c-f66690262673", "transaction_ts": 1511209834}, "payload": {"subscription": {"subscribed_node_id": "c10bf436-ce0f-11e7-8177-f7f4cb18be8b", "phase_criteria": 4, "host": "35.193.45.37", "create_ts": 1511209834, "criteria": ["phase"], "node_owner": "NemoTechnologies", "port": "8083"}}, "signature": {"stripped_hash": "26762e212d5db1c7528879aa1ca84543088692ef402f984f7b75518e55e5714d9aaa18ccbacbe4c585fc08eae4555947103dcdbb247e8d8c4b733df556c256de", "hash": "176f55e805991ef1ee12cc15c81e9269178ffa0ecc311ea60082fea161176f2203b71675a8ec62788584a5cfcf1a1371e474dedc8eb8e497c25d61e458f4c93c", "public_key": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjg1wgX9bkIyvq1s3RCsKXH4SZTrr\nTCHxv1l9Lix+FHbWMUAG2WPzMtBzUkpO0Me7hB8A4gURko5t+PpFTu+lQg==\n-----END PUBLIC KEY-----\n", "signature_ts": 1511209834, "signatory": "transaction-service", "signature": "JB2Csju4j6B/a7l8GGTBKZ1sPN4byt8h/ocH9n2cS5+Wbwzt6cV0Bv0/I3kfLdJ/enWBuA5363zo\nsPLC5cedQw==\n"}}
```
Node0 (failing) subscription request from node1:

```
{
  "header": {
    "create_ts": XXXXXXXXX,
    "business_unit": "NemoTechnologies",
    "family_of_business": "NemoTechnologies",
    "line_of_business": "NemoTechnologies",
    "owner": "NemoTechnologies",
    "transaction_type": "TT_SUB_REQ",
    "actor": "NemoTechnologies",
    "entity": "NemoTechnologies"
  },
  "payload": {
    "subscription": {
      "create_ts": XXXXXXXXX,
      "criteria": ["phase"],
      "phase_criteria": 4,
      "subscribed_node_id": "8a7b667a-ce11-11e7-8484-d7d79ad3d5b2",
      "node_owner": "NemoTechnologies",
      "host": "71.52.69.194",
      "port": "8083"
    }
  }
}
```
sub to node 1 from node 0:
```
{
  "header": {
    "create_ts": XXXXXXXXX,
    "business_unit": "NemoTechnologies",
    "family_of_business": "NemoTechnologies",
    "line_of_business": "NemoTechnologies",
    "owner": "NemoTechnologies",
    "transaction_type": "TT_SUB_REQ",
    "actor": "NemoTechnologies",
    "entity": "NemoTechnologies"
  },
  "payload": {
    "subscription": {
      "create_ts": XXXXXXXXX,
      "criteria": ["phase"],
      "phase_criteria": 4,
      "subscribed_node_id": "c10bf436-ce0f-11e7-8177-f7f4cb18be8b",
      "node_owner": "NemoTechnologies",
      "host": "35.193.45.37",
      "port": "8083"
    }
  }
}
```

Sometimes node0 approves.

I tried to remove all the nodes from config, manually adding subscriptions with no nodes in config except localhost....

Same exact everything. Wiping my DB again and will retry.

**Comment by Gr1dd** [comment]
Wiped both databases, re-cloned, now the error appears to be consistent across both nodes:
```
db_1           |                                    pass_phrase
db_1           |                                  ) VALUES  ('c10bf436-ce0f-11e7-8177-f7f4cb18be8b', to_timestamp(1511214896), 'NemoTechnologies', '35.193.45.37', '8080', 1::BIT(5), 0, NULL)
processor1_1   | Phase 1 Verify Start.
processor1_1   | Time bounds: 1511214895 - 1511214900
processor3_1   | ERROR:apscheduler.executors.default:Job "ConnectionManager.timed_receipt_request (trigger: cron[second='*/300'], next run at: 2017-11-20 21:56:00 UTC)" raised an exception
processor3_1   | Traceback (most recent call last):
processor3_1   |   File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
processor3_1   |     retval = job.func(*job.args, **job.kwargs)
processor3_1   |   File "/opt/dragonchain/blockchain/network.py", line 512, in timed_receipt_request
processor3_1   |     vrs = self.get_vrs(node, ver_ids)  # verifications matching given verification ids
processor3_1   |   File "/opt/dragonchain/blockchain/network.py", line 625, in get_vrs
processor3_1   |     verifications = node.client.transfer_data(node.pass_phrase, received, unreceived)
processor3_1   |   File "/opt/dragonchain/blockchain/gen/messaging/BlockchainService.py", line 419, in transfer_data
processor3_1   |     return self.recv_transfer_data()
processor3_1   |   File "/opt/dragonchain/blockchain/gen/messaging/BlockchainService.py", line 444, in recv_transfer_data
processor3_1   |     raise TApplicationException(TApplicationException.MISSING_RESULT, "transfer_data failed: unknown result")
processor3_1   | TApplicationException: transfer_data failed: unknown result
processor3_1   | WARNING:network-manager:Subscription[sub_id:889cd76b-f9a4-4154-a60b-c9480bc2a8da][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor4_1   | WARNING:network-manager:Subscription[sub_id:889cd76b-f9a4-4154-a60b-c9480bc2a8da][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor2_1   | WARNING:network-manager:Subscription[sub_id:889cd76b-f9a4-4154-a60b-c9480bc2a8da][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
processor1_1   | WARNING:network-manager:Subscription[sub_id:889cd76b-f9a4-4154-a60b-c9480bc2a8da][node_id:8a7b667a-ce11-11e7-8484-d7d79ad3d5b2][node_owner:NemoTechnologies] still in pending status... Waiting for admin(s) approval.
db_1           | ERROR:  duplicate key value violates unique constraint "nodes_pkey"
db_1           | DETAIL:  Key (node_id)=(c10bf436-ce0f-11e7-8177-f7f4cb18be8b) already exists.
db_1           | STATEMENT:  INSERT into nodes (
db_1           |                                    node_id,
db_1           |                                    create_ts,
db_1           |                                    node_owner,
db_1           |                                    host,
db_1           |                                    port,
db_1           |                                    phases,
db_1           |                                    latency,
db_1           |                                    pass_phrase
db_1           |                                  ) VALUES  ('c10bf436-ce0f-11e7-8177-f7f4cb18be8b', to_timestamp(1511214900), 'NemoTechnologies', '35.193.45.37', '8080', 1::BIT(5), 0, NULL)
db_1           | ERROR:  duplicate key value violates unique constraint "nodes_pkey"
db_1           | DETAIL:  Key (node_id)=(c10bf436-ce0f-11e7-8177-f7f4cb18be8b) already exists.
db_1           | STATEMENT:  INSERT into nodes (
```

**Comment by Gr1dd** [comment]
At first, I regenerated thrift (for the first time actually....) I set SQL to 'approved' instead of pending in one of the python files for subscription insertion.

Then I regenrated thrift files.... rebuilt... At first was flooded with all types of errors in console then this:

```
processor1_1   | Phase 1 Verify Start.
processor1_1   | Time bounds: 1511242555 - 1511242560
processor3_1   | c10bf436-ce0f-11e7-8177-f7f4cb18be8b rejected outbound connection request.
processor1_1   | c10bf436-ce0f-11e7-8177-f7f4cb18be8b rejected outbound connection request.
processor2_1   | c10bf436-ce0f-11e7-8177-f7f4cb18be8b rejected outbound connection request.
processor4_1   | c10bf436-ce0f-11e7-8177-f7f4cb18be8b rejected outbound connection request.

```

**Comment by Gr1dd** [comment]
Adding nodes back to my config...

Why must they be in config to have transaction status approved?
I'd rather just subscribe without adding to config, seems so extremely redundant.

**Comment by Gr1dd** [comment]
"processor1_1   | ERROR:apscheduler.executors.default:Job "trigger_handler (trigger: cron[second='*/5'], next run at: 2017-11-21 11:19:00 UTC)" raised an exception
processor1_1   | Traceback (most recent call last):
processor1_1   |   File "/usr/lib64/python2.7/site-packages/apscheduler/executors/base.py", line 108, in run_job
processor1_1   |     retval = job.func(*job.args, **job.kwargs)
processor1_1   |   File "processing.py", line 163, in trigger_handler
processor1_1   |     self.notify(event_name=1, current_block_id=get_current_block_id())
processor1_1   |   File "processing.py", line 126, in notify
processor1_1   |     observer["callback"](config=observer["config"], **kwargs)
processor1_1   |   File "processing.py", line 322, in _execute_phase_1
processor1_1   |     self.network.send_block(self.network.phase_1_broadcast, block_info, phase)
processor1_1   |   File "/opt/dragonchain/blockchain/network.py", line 438, in send_block
processor1_1   |     phase_broadcast(block_info, phase_type)
processor1_1   |   File "/opt/dragonchain/blockchain/network.py", line 445, in phase_1_broadcast
processor1_1   |     for node in self.peer_dict[phase_type]:
processor1_1   | KeyError: 2
"

Giving up. Too many errors in this project to actually benefit anybody at all. Have fun.
